# External Gems
gems: 						[jekyll-paginate]


# Site Settings
title: 						"Coding Notes"
email: 						"mauricio@bithive.io"
description: 				"Welcome to my coding notes, a place where I share my development experiences with the world."
baseurl: 					""
logourl: 					"/assets/img/authorimage.jpg"
fa-logo: 					"fa-code"
paginate: 					5


# Author Settings
author_name: 				"Mauricio"
author_url: 				"http://mauriciopayetta.com"
author_bio: 				"Mauricio is an experienced fullstack developer who loves travelling and learning new technologies. He has been part of the Lending Club, TomTom and Dianrong engineering teams."
author_email: 				"mauricio@bithive.io"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com/mpayetta"
facebook_url: 				"http://facebook.com/mpayetta"
github_url:  				"http://github.com/mpayetta"
linkedin_url:  				"http://linkedin.com/mpayetta"


# Theme Settings
theme_disqus_shortname: 	"codingdiary"
theme_google_comments: 		false
theme_analytics_id: 		""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

